version: "3"

services:
  rnp-ta.org:
    image: ghcr.io/italia/spid-cie-oidc-django:latest
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./examples-docker/rnp_ta:/django-project
    networks:
      - oidcfed
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8000"

  cie-provider.org:
    image: ghcr.io/italia/spid-cie-oidc-django:latest
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    expose:
      - 8002
    ports:
      - "8002:8002"
    volumes:
      - ./examples-docker/provider:/django-project
    networks:
      - oidcfed
    depends_on:
      - rnp-ta.org
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8002"

  relying-party.org:
    image: ghcr.io/italia/spid-cie-oidc-django:latest
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    expose:
      - 8001
    ports:
      - "8001:8001"
    volumes:
      - ./examples-docker/relying_party:/django-project
    networks:
      - oidcfed
    depends_on:
      - rnp-ta.org
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8001"

  ufrgs-ta.org:
    image: ghcr.io/italia/spid-cie-oidc-django:latest
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./examples-docker/ufrgs_ta:/django-project
    networks:
      - oidcfed
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/ta-ec.json &&
        python3 manage.py runserver 0.0.0.0:8005"

  ufrgs-sp.org:
    # image: ghcr.io/italia/spid-cie-oidc-django:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8006
    ports:
      - "8006:8006"
    volumes:
      - ./examples-docker/ufrgs_sp:/django-project
      # - ./spid_cie_oidc/relying_party:/django-project/spid_cie_oidc/relying_party
      - ./spid_cie_oidc:/usr/local/lib/python3.10/site-packages/spid_cie_oidc
    networks:
      - oidcfed
    depends_on:
      - ufrgs-ta.org
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example.json &&
        python3 manage.py runserver 0.0.0.0:8006"
networks:
  oidcfed:
